import type {
  Participante,
  ParticipanteRepository,
  RegistrarParticipanteInput,
} from '@modules/participantes/domain/types'
import { mockLatency } from '@shared/api/mockLatency'

/** Bump de versión para forzar reseed cuando cambia el mock. */
const STORAGE_KEY = 'reclutadoras.mock.participantes.v6'

function daysAgo(days: number) {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

const SEED: Participante[] = [
  {
    id: 'p1',
    proyectoId: 'form1',
    nombre: 'Ana Pérez Gómez',
    tipoDocumento: 'CC',
    documento: '1020304050',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3001234567',
    estado: 'EN_FILTRO',
    camposExtra: { nombre_bebe: 'Mateo', genero_bebe: 'Masculino' },
    observaciones: "Pendiente confirmar disponibilidad para la visita de screening la próxima semana.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(1),
  },
  {
    id: 'p2',
    proyectoId: 'form1',
    nombre: 'Laura Jiménez Ríos',
    tipoDocumento: 'CC',
    documento: '52987654',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3014455667',
    estado: 'APROBADO',
    camposExtra: { nombre_bebe: 'Sofía', genero_bebe: 'Femenino' },
    observaciones: "Cumple todos los criterios. Documentación completa.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(2),
  },
  {
    id: 'p3',
    proyectoId: 'form1',
    nombre: 'María Fernanda López',
    tipoDocumento: 'CC',
    documento: '1034567890',
    genero: 'Femenino',
    ciudad: 'Medellín',
    telefono: '3127788990',
    estado: 'RECHAZADO',
    camposExtra: { nombre_bebe: 'Samuel', genero_bebe: 'Masculino' },
    observaciones: "No cumple criterio de edad gestacional mínima.",
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(3),
  },
  {
    id: 'p4',
    proyectoId: 'form1',
    nombre: 'Camila Andrea Torres',
    tipoDocumento: 'CE',
    documento: 'E-88442211',
    genero: 'Femenino',
    ciudad: 'Cali',
    telefono: '3152233445',
    estado: 'NO_CONTESTA',
    camposExtra: { nombre_bebe: 'Valentina', genero_bebe: 'Femenino' },
    observaciones: "Se intentó contacto en 3 ocasiones sin respuesta.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(1),
  },
  {
    id: 'p5',
    proyectoId: 'form1',
    nombre: 'Diana Carolina Mejía',
    tipoDocumento: 'CC',
    documento: '43789123',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3209988776',
    estado: 'EN_FILTRO',
    camposExtra: { nombre_bebe: 'Martín', genero_bebe: 'Masculino' },
    observaciones: "Revisar consentimiento informado antes de agendar.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(0),
  },
  {
    id: 'p6',
    proyectoId: 'form1',
    nombre: 'Paola Andrea Castro',
    tipoDocumento: 'CC',
    documento: '1012345678',
    genero: 'Femenino',
    ciudad: 'Medellín',
    telefono: '3005566778',
    estado: 'APROBADO',
    camposExtra: { nombre_bebe: 'Isabella', genero_bebe: 'Femenino' },
    observaciones: "Aprobada en segundo filtro. Lista para cita.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(4),
  },
  {
    id: 'p7',
    proyectoId: 'form1',
    nombre: 'Juliana Restrepo Quintero',
    tipoDocumento: 'CC',
    documento: '1152003344',
    genero: 'Femenino',
    ciudad: 'Cali',
    telefono: '3186677889',
    estado: 'EN_FILTRO',
    camposExtra: { nombre_bebe: 'Emilio', genero_bebe: 'Masculino' },
    observaciones: "Madre solicita llamada en horario nocturno.",
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(2),
  },
  {
    id: 'p8',
    proyectoId: 'form1',
    nombre: 'Natalia Vargas Duque',
    tipoDocumento: 'CC',
    documento: '52881122',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3112345678',
    estado: 'P_PACIENTE_FALLECIDO',
    camposExtra: { nombre_bebe: 'Lucas', genero_bebe: 'Masculino' },
    observaciones: "Caso cerrado por deceso del paciente.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(6),
  },
  {
    id: 'p9',
    proyectoId: 'form1',
    nombre: 'Carolina Suárez Peña',
    tipoDocumento: 'CE',
    documento: 'E-99112233',
    genero: 'Femenino',
    ciudad: 'Medellín',
    telefono: '3041122334',
    estado: 'RECHAZADO',
    camposExtra: { nombre_bebe: 'Emma', genero_bebe: 'Femenino' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(5),
  },
  {
    id: 'p10',
    proyectoId: 'form1',
    nombre: 'Andrea Milena Rojas',
    tipoDocumento: 'CC',
    documento: '1098765432',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3178899001',
    estado: 'NO_CONTESTA',
    camposExtra: { nombre_bebe: 'Thiago', genero_bebe: 'Masculino' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(3),
  },
  {
    id: 'p11',
    proyectoId: 'form1',
    nombre: 'Viviana Alejandra Ortiz',
    tipoDocumento: 'CC',
    documento: '43215678',
    genero: 'Femenino',
    ciudad: 'Cali',
    telefono: '3024455667',
    estado: 'APROBADO',
    camposExtra: { nombre_bebe: 'Olivia', genero_bebe: 'Femenino' },
    observaciones: '',
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(7),
  },
  {
    id: 'p12',
    proyectoId: 'form1',
    nombre: 'Sandra Liliana Giraldo',
    tipoDocumento: 'CC',
    documento: '1044556677',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3196677880',
    estado: 'EN_FILTRO',
    camposExtra: { nombre_bebe: 'Benjamín', genero_bebe: 'Masculino' },
    observaciones: "Datos actualizados tras segundo contacto.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(0),
  },
  {
    id: 'p13',
    proyectoId: 'form2',
    nombre: 'Carlos Ruiz Mendoza',
    tipoDocumento: 'CE',
    documento: '1122334455',
    genero: 'Masculino',
    ciudad: 'Barranquilla',
    telefono: '3109876543',
    estado: 'NO_CONTESTA',
    camposExtra: { producto_actual: 'Analgésico X' },
    observaciones: "No responde WhatsApp; intentar llamada telefónica.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(2),
  },
  {
    id: 'p14',
    proyectoId: 'form2',
    nombre: 'Héctor Fabio Ramírez',
    tipoDocumento: 'CC',
    documento: '79884556',
    genero: 'Masculino',
    ciudad: 'Bogotá',
    telefono: '3007788990',
    estado: 'EN_FILTRO',
    camposExtra: { producto_actual: 'Ibuprofeno' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(1),
  },
  {
    id: 'p15',
    proyectoId: 'form2',
    nombre: 'Gloria Esperanza Díaz',
    tipoDocumento: 'CC',
    documento: '41556677',
    genero: 'Femenino',
    ciudad: 'Cali',
    telefono: '3165544332',
    estado: 'APROBADO',
    camposExtra: { producto_actual: 'Acetaminofén' },
    observaciones: '',
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(4),
  },
  {
    id: 'p16',
    proyectoId: 'form2',
    nombre: 'Ricardo Andrés Molina',
    tipoDocumento: 'CC',
    documento: '80112233',
    genero: 'Masculino',
    ciudad: 'Medellín',
    telefono: '3012233445',
    estado: 'RECHAZADO',
    camposExtra: { producto_actual: 'Naproxeno' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(3),
  },
  {
    id: 'p17',
    proyectoId: 'form2',
    nombre: 'Martha Lucía Beltrán',
    tipoDocumento: 'CC',
    documento: '39667788',
    genero: 'Femenino',
    ciudad: 'Barranquilla',
    telefono: '3148899001',
    estado: 'EN_FILTRO',
    camposExtra: { producto_actual: 'Diclofenaco' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(0),
  },
  {
    id: 'p18',
    proyectoId: 'form2',
    nombre: 'Jorge Iván Pardo',
    tipoDocumento: 'CE',
    documento: 'E-55667788',
    genero: 'Masculino',
    ciudad: 'Bogotá',
    telefono: '3201122334',
    estado: 'NO_CONTESTA',
    camposExtra: { producto_actual: 'Analgésico Y' },
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(5),
  },
  {
    id: 'p19',
    proyectoId: 'form3',
    nombre: 'Elena Patricia Niño',
    tipoDocumento: 'CC',
    documento: '52114455',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3103344556',
    estado: 'APROBADO',
    camposExtra: {},
    observaciones: "Observación de prueba para validar la sección del popup.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(2),
  },
  {
    id: 'p20',
    proyectoId: 'form3',
    nombre: 'Felipe Andrés Cárdenas',
    tipoDocumento: 'CC',
    documento: '1022334455',
    genero: 'Masculino',
    ciudad: 'Medellín',
    telefono: '3156677889',
    estado: 'EN_FILTRO',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(1),
  },
  {
    id: 'p21',
    proyectoId: 'form3',
    nombre: 'Rosa María Aguilar',
    tipoDocumento: 'CC',
    documento: '40998877',
    genero: 'Femenino',
    ciudad: 'Cali',
    telefono: '3009988776',
    estado: 'RECHAZADO',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(6),
  },
  {
    id: 'p22',
    proyectoId: 'form4',
    nombre: 'Tatiana Marcela León',
    tipoDocumento: 'CC',
    documento: '1033445566',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3184455667',
    estado: 'EN_FILTRO',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(0),
  },
  {
    id: 'p23',
    proyectoId: 'form4',
    nombre: 'Óscar Daniel Pinzón',
    tipoDocumento: 'CC',
    documento: '79445566',
    genero: 'Masculino',
    ciudad: 'Barranquilla',
    telefono: '3015566778',
    estado: 'APROBADO',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(3),
  },
  {
    id: 'p24',
    proyectoId: 'form5',
    nombre: 'Lina Marcela Hoyos',
    tipoDocumento: 'CC',
    documento: '52889900',
    genero: 'Femenino',
    ciudad: 'Medellín',
    telefono: '3123344556',
    estado: 'NO_CONTESTA',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'coordinadora',
    creadoEn: daysAgo(2),
  },
  {
    id: 'p25',
    proyectoId: 'form5',
    nombre: 'Sebastián Mauricio Vélez',
    tipoDocumento: 'CE',
    documento: 'E-33445566',
    genero: 'Masculino',
    ciudad: 'Cali',
    telefono: '3177788990',
    estado: 'EN_FILTRO',
    camposExtra: {},
    observaciones: '',
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(1),
  },
  {
    id: 'p26',
    proyectoId: 'form5',
    nombre: 'Adriana Patricia Muñoz',
    tipoDocumento: 'CC',
    documento: '43556677',
    genero: 'Femenino',
    ciudad: 'Bogotá',
    telefono: '3049988776',
    estado: 'APROBADO',
    camposExtra: {},
    observaciones: "Participante confirmó asistencia al estudio.",
    creadoPor: 'reclutadora',
    creadoEn: daysAgo(4),
  },
]

function readStore(): Participante[] {
  const raw = localStorage.getItem(STORAGE_KEY)
  if (!raw) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(SEED))
    return structuredClone(SEED)
  }

  try {
    const parsed = JSON.parse(raw) as Participante[]
    return parsed.map((item) => ({
      ...item,
      tipoDocumento: item.tipoDocumento ?? '',
      genero: item.genero ?? '',
      observaciones: item.observaciones ?? '',
    }))
  } catch {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(SEED))
    return structuredClone(SEED)
  }
}

function writeStore(items: Participante[]) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(items))
}

export class MockParticipanteRepository implements ParticipanteRepository {
  async list(filters?: { proyectoId?: string; estado?: string }): Promise<Participante[]> {
    await mockLatency()
    return readStore().filter((item) => {
      if (filters?.proyectoId && item.proyectoId !== filters.proyectoId) return false
      if (filters?.estado && item.estado !== filters.estado) return false
      return true
    })
  }

  async register(input: RegistrarParticipanteInput): Promise<Participante> {
    await mockLatency(160)
    const created: Participante = {
      id: `p-${crypto.randomUUID()}`,
      proyectoId: input.proyectoId,
      nombre: input.nombre,
      tipoDocumento: input.tipoDocumento,
      documento: input.documento,
      genero: input.genero,
      ciudad: input.ciudad,
      telefono: input.telefono,
      estado: 'EN_FILTRO',
      camposExtra: input.camposExtra,
      observaciones: input.observaciones?.trim() ?? '',
      creadoPor: input.creadoPor,
      creadoEn: new Date().toISOString(),
    }

    const list = readStore()
    list.unshift(created)
    writeStore(list)
    return created
  }
}
